### ISSUE TITLE
the tutorial code does not work

### ISSUE THREAD

**Issue by Pomax** [paperjs/paperjs.org#11]
The initial tutorial code on http://paperjs.org/tutorials/getting-started/working-with-paper-js, 
```
<!DOCTYPE html>
<html>
<head>
<!-- Load the Paper.js library -->
<script type="text/javascript" src="js/paper.js"></script>
<!-- Define inlined PaperScript associate it with myCanvas -->
<script type="text/paperscript" canvas="myCanvas">
	// Create a Paper.js Path to draw a line into it:
	var path = new Path();
	// Give the stroke a color
	path.strokeColor = 'black';
	var start = new Point(100, 100);
	// Move to start and draw a line from there
	path.moveTo(start);
	// Note the plus operator on Point objects.
	// PaperScript does that for us, and much more!
	path.lineTo(start + [ 100, -50 ]);
</script>
</head>
<body>
	<canvas id="myCanvas" resize></canvas>
</body>
</html>
```
does not work with paperjs 0.9.23, instead throwing a parse error about a missing `]`, as can be seen in this jsbin: http://jsbin.com/kedixufiye/edit?html,output

**Comment by lehni** [comment]
I think there was something going wrong with and older versin of uglifyjs, the minifier we use. I republished a correct version while I really should have bumped the version number. Try loading the non-minified version from cloud fare to see if that fixes it.

**Comment by Pomax** [comment]
indeed, unminified works.http://jsbin.com/zawoquzika/edit?html,output

**Comment by lehni** [comment]
Great, thanks for confirming. Time for a new version then!
