### ISSUE TITLE
All website examples are down

### ISSUE THREAD

**Issue by hovavo** [paperjs/paperjs.org#19]
Looks like the latest build is missing some stuff:

paper.js:27 GET http://paperjs.org/assets/node_modules/prepro/lib/browser.js 
paper.js:31 GET http://paperjs.org/assets/src/load.js 404 (Not Found)
scripts.js:303 Uncaught ReferenceError: paper is not defined

**Comment by lehni** [comment]
Yes I'm aware of it. I was out the whole day and am looking into it now.

**Comment by lehni** [comment]
It's fixed and back up. You might have to force a reload.

**Comment by hovavo** [comment]
Awesome, thanks!
