### ISSUE TITLE
Animations using js

### ISSUE THREAD

**Issue by QuinDennis** [paperjs/paperjs.org#22]
Doesn't look like paper.js works with animation via JS.  The onFrame below works as expected, using setInterval and rotate doesn't rotate.  However, moving the mouse over the rect causes it to advance 3 degrees as long as the mouse is moving.

(I'm coming from snap.svg where rotations work as expected)

paper.install(window)
window.onload = function() {
    paper.setup('myCanvas')
    var rect = new Path.Rectangle([75,75], [100,100])
    rect.strokeColor = 'black'
    
    //view.onFrame = function(event) {
    //    rect.rotate(3)
    //}
    setInterval(function(){
        rect.rotate(3)}, 500)
}

**Comment by lehni** [comment]
You need to update the view if you use events that are outside of what paper.js offers:

Just add this and it will work as expected:

```js
view.update();
```

PS: This is a bug database. Support questions should go to the mailing list http://groups.google.com/group/paperjs

**Comment by QuinDennis** [comment]
Wow, thanks for the prompt response!  I began to suspect there was a 
solution like that, just hadn't learned enough about it yet.  Nice library!

On 07/12/2016 02:51 AM, Jürg Lehni wrote:
>
> You need to update the view if you use events that are outside of what 
> paper.js offers:
>
> Just add this and it will work as expected:
>
> view.update();
>
> PS: This is a bug database. Support questions should go to the mailing 
> list http://groups.google.com/group/paperjs
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/paperjs/paperjs.org/issues/22#issuecomment-231964713>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AAx1kULDryOTbLtpLcmuLS0VL6iIRqTVks5qU0d8gaJpZM4JJvcf>.
>

-- 
Quin Dennis | t: 512.392.8619

**Comment by QuinDennis** [comment]
Sorry to bother you again, but animating has a big memory leak.  Using
Update or onFrame,

On Tue, Jul 12, 2016 at 8:05 AM, Quin Dennis <quindennis@gmail.com> wrote:

> Wow, thanks for the prompt response!  I began to suspect there was a
> solution like that, just hadn't learned enough about it yet.  Nice library!
>
>
> On 07/12/2016 02:51 AM, Jürg Lehni wrote:
>
> You need to update the view if you use events that are outside of what
> paper.js offers:
>
> Just add this and it will work as expected:
>
> view.update();
>
> PS: This is a bug database. Support questions should go to the mailing
> list http://groups.google.com/group/paperjs
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/paperjs/paperjs.org/issues/22#issuecomment-231964713>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAx1kULDryOTbLtpLcmuLS0VL6iIRqTVks5qU0d8gaJpZM4JJvcf>
> .
>
>
> --
> Quin Dennis | t: 512.392.8619
>



-- 
Quin Dennis | t: 512-392-8619 | c: 512-214-3193

**Comment by QuinDennis** [comment]
Sorry to bother you again, but animating has a big memory leak.  Using
Update or onFrame, memory and CPU usage reaches critical levels within 15
seconds.  Is there something I'm missing?  Is this a Bug?

On Tue, Jul 12, 2016 at 12:25 PM, Quin Dennis <quindennis@gmail.com> wrote:

> Sorry to bother you again, but animating has a big memory leak.  Using
> Update or onFrame,
>
> On Tue, Jul 12, 2016 at 8:05 AM, Quin Dennis <quindennis@gmail.com> wrote:
>
>> Wow, thanks for the prompt response!  I began to suspect there was a
>> solution like that, just hadn't learned enough about it yet.  Nice library!
>>
>>
>> On 07/12/2016 02:51 AM, Jürg Lehni wrote:
>>
>> You need to update the view if you use events that are outside of what
>> paper.js offers:
>>
>> Just add this and it will work as expected:
>>
>> view.update();
>>
>> PS: This is a bug database. Support questions should go to the mailing
>> list http://groups.google.com/group/paperjs
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/paperjs/paperjs.org/issues/22#issuecomment-231964713>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AAx1kULDryOTbLtpLcmuLS0VL6iIRqTVks5qU0d8gaJpZM4JJvcf>
>> .
>>
>>
>> --
>> Quin Dennis | t: 512.392.8619
>>
>
>
>
> --
> Quin Dennis | t: 512-392-8619 | c: 512-214-3193
>



-- 
Quin Dennis | t: 512-392-8619 | c: 512-214-3193

**Comment by lehni** [comment]
This issue is closed. Support questions should go to the mailing list, please: http://groups.google.com/group/paperjs
