### ISSUE TITLE
Links point to pages from scriptographer.org

### ISSUE THREAD

**Issue by MohammadHejazi** [paperjs/paperjs.org#29]
There are some links that point to scriptographer.org, despite the linked articles are also available on paperjs.org like here:

https://github.com/paperjs/paperjs.org/blob/dbb416f11f199107cbde670dccd35f065d50b6a9/content/02-Features/page.txt#L116

```
http://scriptographer.org/tutorials/interaction/creating-mouse-tools/
http://       paperjs.org/tutorials/interaction/creating-mouse-tools/
```

Is this intended or needs to be fixed?

P.S. You can find other similar links by searching for  `scriptographer.org`:
https://github.com/paperjs/paperjs.org/search?q=scriptographer

**Comment by lehni** [comment]
@MohammadHejazi thanks for pointing this out, and apologies for taking so long to fix it.
