### ISSUE TITLE
how to create pattern for strokeStyle in Paper.js

### ISSUE THREAD

**Issue by zousandian** [paperjs/paperjs.org#8]
I can create pattern for the stroke like this in Javascript:
<pre>var img = new Image();
img.src = "xx.png";

img.onload = function(){

  var pattern = ctx.createPattern(img, "repeat");
  ctx.strokeStyle=pattern;

  ctx.lineWidth = 30;

  ctx.beginPath();
  ctx.moveTo(100,0)
  ctx.lineTo(100,300);

  ctx.stroke();
}</pre>
How can i create pattern  for Path items created with Paper.js?

**Comment by lehni** [comment]
There is no support for patterns in paper.js yet, and this is the wrong place for such requests.

There is an issue for it here: https://github.com/paperjs/paper.js/issues/829
And requests for support go here: http://groups.google.com/group/paperjs
